# GCP Settings
gcp_project   = "velvety-byway-385815"
gcp_region    = "us-central1"
gcp_zone    = "us-central1-c"
gcp_auth_file = "./terragcp.json"
# GCP Netwok
network-subnet-cidr = "10.10.10.0/24"
# Linux VM
linux_instance_type = "f1-micro"
